color0 #121508
color1 #ffb4ab
color2 #ffb958
color3 #f6bc70
color4 #bdce80
color5 #ffb958
color6 #f6bc70
color7 #e2e4cf
color8 #8e9475
color9 #ffb4ab
color10 #ffb958
color11 #f6bc70
color12 #bdce80
color13 #ffb958
color14 #f6bc70
color15 #e2e4cf

cursor                #e2e4cf
cursor_text_color     #121508
background            #121508
foreground            #e2e4cf
selection_foreground  #c4caa9
selection_background  #444930
active_border_color   #ffb958
inactive_border_color #444930
url_color             #ffb958

active_tab_foreground   #462b00
active_tab_background   #ffb958
inactive_tab_foreground #c4caa9
inactive_tab_background #444930
cursor_trail_color      #c4caa9
