color0 #fff8f3
color1 #ba1a1a
color2 #9c4332
color3 #904b3e
color4 #7c580d
color5 #ffb4a6
color6 #ffb4a6
color7 #221a0d
color8 #887456
color9 #ba1a1a
color10 #9c4332
color11 #904b3e
color12 #7c580d
color13 #ffb4a6
color14 #ffb4a6
color15 #221a0d

cursor                #221a0d
cursor_text_color     #fff8f3
background            #fff8f3
foreground            #221a0d
selection_foreground  #55442a
selection_background  #f8dfbb
active_border_color   #9c4332
inactive_border_color #f8dfbb
url_color             #9c4332

active_tab_foreground   #ffffff
active_tab_background   #9c4332
inactive_tab_foreground #55442a
inactive_tab_background #f8dfbb
cursor_trail_color      #55442a
